Issues #1273, #1277, #1320
ImagingDataCommons/IDC-WebApp pull request #1330
Opened 2023-11-17 21:56 UTC by G-White-ISB

Change tooltips to popups for analytics collections. Address bugs #1273, #1320

2023-11-20 18:02 UTC, s-paquette requested changes

2023-11-20 18:02 UTC, s-paquette commented on static/js/image_search.js
> +    $('.collection_info, analysis_info').on("mouseenter", function(e){
Missing `.` on analysis_info

2023-11-20 18:02 UTC, s-paquette commented on static/js/image_search.js
> +    $('.collection_info, analysis_info').on("mouseleave", function(e){
As above--missing `.` on analysis_info

2023-11-21 17:36 UTC, G-White-ISB commented
Changes made. Please review again

2023-11-21 18:53 UTC, merged